
package com.suhael.jaxws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CRUDSoap", targetNamespace = "http://service.jaxws.suhael.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.CreateResponse")
    public String create();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.DeleteResponse")
    public String delete();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws CustomException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.ReadResponse")
    public String read(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws CustomException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.jaxws.suhael.com/", className = "com.suhael.jaxws.service.UpdateResponse")
    public String update();

}
