
package com.suhael.jaxws.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CRUDSoapService", targetNamespace = "http://service.jaxws.suhael.com/", wsdlLocation = "http://localhost:7001/jaxwsServer/CRUDSoapService?WSDL")
public class CRUDSoapService
    extends Service
{

    private final static URL CRUDSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.suhael.jaxws.service.CRUDSoapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.suhael.jaxws.service.CRUDSoapService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/jaxwsServer/CRUDSoapService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/jaxwsServer/CRUDSoapService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CRUDSOAPSERVICE_WSDL_LOCATION = url;
    }

    public CRUDSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRUDSoapService() {
        super(CRUDSOAPSERVICE_WSDL_LOCATION, new QName("http://service.jaxws.suhael.com/", "CRUDSoapService"));
    }

    /**
     * 
     * @return
     *     returns CRUDSoap
     */
    @WebEndpoint(name = "CRUDSoapPort")
    public CRUDSoap getCRUDSoapPort() {
        return super.getPort(new QName("http://service.jaxws.suhael.com/", "CRUDSoapPort"), CRUDSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDSoap
     */
    @WebEndpoint(name = "CRUDSoapPort")
    public CRUDSoap getCRUDSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.jaxws.suhael.com/", "CRUDSoapPort"), CRUDSoap.class, features);
    }

}
