
package com.suhael.jaxws.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CustomException", targetNamespace = "http://service.jaxws.suhael.com/")
public class CustomException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CustomException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CustomException_Exception(String message, CustomException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CustomException_Exception(String message, CustomException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.suhael.jaxws.service.CustomException
     */
    public CustomException getFaultInfo() {
        return faultInfo;
    }

}
